"use client";

import { useState } from "react";
import { api } from "../../lib/api";

const initial = { applicantName: "", applicantAadharNumber: "", applicantMobileNumber: "", permanentAddress: "", email: "", deadPersonName: "", gender: "", deathDate: "", deathPlace: "", deadPersonAadharNumber: "", motherName: "", fatherHusbandName: "" };

export default function DeathRegisterPage() {
  const [form, setForm] = useState(initial), [phase, setPhase] = useState("form"), [message, setMessage] = useState(""), [busy, setBusy] = useState(false), [temp, setTemp] = useState(""), [docs, setDocs] = useState([]), [uploaded, setUploaded] = useState({}), [number, setNumber] = useState("");
  const update = (key) => (e) => setForm((v) => ({ ...v, [key]: e.target.value }));
  const submit = async () => { setBusy(true); setMessage(""); try { const r = await api.death.createTemp({ ...form, deathDate: form.deathDate || null, gender: form.gender || null }); setTemp(r.tempApplicationNumber); setDocs(r.requiredDocuments || []); setMessage(r.message); setPhase("documents"); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const upload = async (key, file) => { if (!file) return; setBusy(true); try { await api.death.uploadDocument(temp, key, file); setUploaded((v) => ({ ...v, [key]: file.name })); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  const finalize = async () => { setBusy(true); try { const r = await api.death.finalize(temp); setNumber(r.applicationNumber); setPhase("success"); } catch (e) { setMessage(e.message); } finally { setBusy(false); } };
  return <div style={card}><h1>Death Registration</h1><Steps phase={phase} />
    {phase === "form" && <section><h3>Applicant</h3><Field label="Applicant Name"><input style={input} value={form.applicantName} onChange={update("applicantName")} /></Field><Field label="Applicant Aadhaar Number"><input style={input} inputMode="numeric" maxLength="14" value={form.applicantAadharNumber} onChange={update("applicantAadharNumber")} /></Field><Field label="Applicant Mobile Number"><input style={input} inputMode="numeric" maxLength="10" value={form.applicantMobileNumber} onChange={update("applicantMobileNumber")} /></Field><Field label="Permanent Address"><input style={input} value={form.permanentAddress} onChange={update("permanentAddress")} /></Field><Field label="Email to Receive Certificate"><input style={input} value={form.email} onChange={update("email")} /></Field><h3>Deceased Person</h3><Field label="Dead Person Name"><input style={input} value={form.deadPersonName} onChange={update("deadPersonName")} /></Field><Field label="Gender"><select style={input} value={form.gender} onChange={update("gender")}><option value="">-- Select --</option><option>Male</option><option>Female</option><option>Other</option></select></Field><Field label="Death Date"><input type="date" style={input} value={form.deathDate} onChange={update("deathDate")} /></Field><Field label="Death Place"><input style={input} value={form.deathPlace} onChange={update("deathPlace")} /></Field><Field label="Dead Person Aadhaar Number"><input style={input} inputMode="numeric" maxLength="14" value={form.deadPersonAadharNumber} onChange={update("deadPersonAadharNumber")} /></Field><h3>Family</h3><Field label="Mother Name"><input style={input} value={form.motherName} onChange={update("motherName")} /></Field><Field label="Father/Husband Name"><input style={input} value={form.fatherHusbandName} onChange={update("fatherHusbandName")} /></Field>{message && <p style={error}>{message}</p>}<button style={btn} disabled={busy} onClick={submit}>{busy ? "Submitting..." : "Continue"}</button></section>}
    {phase === "documents" && <section><h3>Required Documents</h3>{docs.map((d) => <div key={d.key} style={doc}>{d.label}{uploaded[d.key] ? <strong style={{ color: "green" }}>{uploaded[d.key]}</strong> : <input type="file" accept=".pdf,.jpg,.jpeg,.png" disabled={busy} onChange={(e) => upload(d.key, e.target.files?.[0])} />}</div>)}{message && <p style={error}>{message}</p>}<button style={btn} disabled={busy} onClick={finalize}>Upload &amp; Submit</button></section>}
    {phase === "success" && <section><h3>Application Submitted Successfully</h3><p>Your Application Number is:</p><p style={{ fontSize: 24, fontWeight: 700, color: "#0b3d91" }}>{number}</p><a style={btn} href={`/status/${number}`}>Check Status</a></section>}
  </div>;
}
function Steps({ phase }) { const all=["form","documents","success"], labels=["Fill Form","Documents","Done"]; return <div style={{ display:"flex", gap:8, margin:"16px 0 24px" }}>{labels.map((x,i)=><span key={x} style={{ color:all[i]===phase?"#0b3d91":"#777", fontWeight:all[i]===phase?700:400 }}>{i+1}. {x}</span>)}</div>; }
function Field({ label, children }) { return <div style={{ marginBottom: 14 }}><label style={{ display:"block", fontWeight:600, marginBottom:4 }}>{label}</label>{children}</div>; }
const card={ background:"#fff", padding:24, borderRadius:8 }, input={ width:"100%", padding:10, border:"1px solid #ccc", borderRadius:4, fontSize:14 }, btn={ background:"linear-gradient(110deg, #ad5288 0%, #762c70 52%, #42114f 100%)", color:"#fff", padding:"10px 20px", border:"none", borderRadius:6, fontWeight:600, cursor:"pointer", textDecoration:"none", display:"inline-block" }, error={ color:"crimson" }, doc={ display:"flex", justifyContent:"space-between", padding:"12px 0", borderBottom:"1px solid #eee" };
